import com.project.droolsdemo.models.CarInsuranceDetails;
import java.util.*;
import java.math.BigDecimal;
import com.project.droolsdemo.models.Insurer;
 
 
ruleflow-group "LUW_AIG"
  
rule "FUW_NATIONWIDE-Criteria Based on Manufacturing Date"

lock-on-active true
salience 10
dialect "java"

	when
	    $carInfo:CarInsuranceDetails(manufacturedYear >= "2007" , $amt:cost)
	    $list: ArrayList()
    then
    	System.out.println("FUW_NATIONWIDE RULE 1");
        modify($list){add(new Insurer("FUW_NATIONWIDE",$amt*0.25,"25%"))};   
end

rule "FUW_NATIONWIDE-Criteria Based on Claims Number - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 1 && <3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "FUW_NATIONWIDE") from $list
		
	then
		System.out.println("FUW_NATIONWIDE RULE 2");
	    $amt=$amt*0.20;
	   	$insurer.setAmount($amt);
	   	$insurer.setPercentage("20%");
	   	
end


rule "FUW_NATIONWIDE-Criteria Based on Claims Number - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "FUW_NATIONWIDE") from $list
	then
		System.out.println("FUW_NATIONWIDE RULE 3");
	    $amt=$amt*0.15;
	    $insurer.setAmount($amt);
	    $insurer.setPercentage("15%");
end   

rule "FUW_NATIONWIDE-BajajAllianz-Criteria Based on Claims and Use - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 ,use == "business", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "FUW_NATIONWIDE") from $list
	then
		System.out.println("FUW_NATIONWIDE RULE 4");
	    $amt=$amt*0.10;
	    $insurer.setAmount($amt);
	    $insurer.setPercentage("10%");
end 




	   