import com.project.droolsdemo.models.CarInsuranceDetails;
import java.util.*;
import java.math.BigDecimal;
import com.project.droolsdemo.models.Insurer;
 
 
ruleflow-group "LUW_RSA"
  
rule "FUW_HISCOX-Criteria Based on Manufacturing Date"

lock-on-active true
salience 10
dialect "java"

	when
	    $carInfo:CarInsuranceDetails(manufacturedYear >= "2010",profession =="employed" , $amt:cost)
	    $list: ArrayList()
    then
    	System.out.println("FUW_AMTRUST RULE 1");
        modify($list){add(new Insurer("FUW_HISCOX",$amt*0.15,"15%"))};   
end



rule "FUW_HISCOX-Criteria Based on Claims Number - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 2 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "FUW_HISCOX") from $list
	then
		System.out.println("FUW_HISCOX RULE 3");
	    $amt=$amt*0.10;
	    $insurer.setAmount($amt);
	    $insurer.setPercentage("10%");
end   

rule "FUW_HISCOX-Criteria Based on Claims and Use - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 ,use == "business", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "FUW_HISCOX") from $list
	then
		System.out.println("FUW_HISCOX RULE 4");
	    $amt=$amt*0.05;
	    $insurer.setAmount($amt);
	    $insurer.setPercentage("5%");
end 

rule "FUW_HISCOX-Criteria Based on City-1"
	when
		$carInfo:CarInsuranceDetails(city == "bihar", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "FUW_HISCOX") from $list
	then
		System.out.println("FUW_HISCOX RULE 5");
	    $amt=$amt*0.05;
	    $insurer.setAmount($amt);
	    $insurer.setPercentage("5%");
end 


	   