import com.project.droolsdemo.models.CarInsuranceDetails;
import java.util.*;
import java.math.BigDecimal;
import com.project.droolsdemo.models.Insurer;

dialect "mvel" 

ruleflow-group "default"

rule "LUW_RSA-Criteria Based on Manufacturing Date"
lock-on-active true
salience 10

dialect "java"
	when
	    $carInfo:CarInsuranceDetails(use == "personal" , $amt:cost)
	    $list: ArrayList()
    then
    	System.out.println("RULE 1");
    	$list.add(new Insurer("LUW_RSA",$amt*0.5,"50%"));
        update($list);
end

rule "LUW_RSA-Criteria Based on Claims Number - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 1 && <3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "LUW_RSA") from $list
	then
		System.out.println("RULE 2");
	    $amt=$amt*0.47;
	    $insurer.setAmount($amt);
	    $insurer.setPercentage("37%");
end
	
rule "LUW_RSA-Criteria Based on Claims Number - 2"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 , $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "LUW_RSA") from $list
	then
	System.out.println("RULE 3");
	    $amt=$amt*0.40;
	    $insurer.setAmount($amt);
	    $insurer.setPercentage("40%");
end   

rule "LUW_RSA-Criteria Based on Claims and Year - 1"
	when
		$carInfo:CarInsuranceDetails(claims >= 3 ,manufacturedYear < "2007", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "LUW_RSA") from $list
	then
	System.out.println("RULE 4");
	    $amt=$amt*0.35;
	    $insurer.setAmount($amt);
	    $insurer.setPercentage("35%");
end 

rule "LUW_RSA-Criteria Based on Claims and Year - 2"

	when
		$carInfo:CarInsuranceDetails(claims >= 5 ,manufacturedYear < "2000", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "LUW_RSA") from $list
	then
		System.out.println("RULE 5");
		$list.remove($insurer);
end 
	  

rule "LUW_RSA-Criteria Based on Claims and Gender - 1"

	when
		$carInfo:CarInsuranceDetails(claims >= 2 ,gender == "female", $amt:cost)	
		$list: ArrayList()
		$insurer:Insurer(name == "LUW_RSA") from $list
	then
		System.out.println("RULE 6");
	    $amt=$amt*0.30;
	    $insurer.setAmount($amt);
	    $insurer.setPercentage("30%");
end 
	 